# Generated by Django 5.1.6 on 2025-03-25 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cycle_hours_remaining',
            field=models.DecimalField(decimal_places=1, default=70, max_digits=4),
        ),
        migrations.AddField(
            model_name='trip',
            name='cycle_start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='violations',
            field=models.JSONField(default=list),
        ),
    ]
