# Generated by Django 5.1.6 on 2025-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_cycle_hours_remaining_trip_cycle_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='sleeper_berth_hours',
            field=models.FloatField(default=0),
        ),
    ]
